-- to list database we write \l
-- convention to write capital, CREATE DATABASE
-- end with semicolon
-- \c table_name to connect to a database, like \c products
-- \d to list all the tables 
--  \d table_name to view the structure
-- to add/delete columns in a table, we do: 
-- ALTER TABLE table_name 
-- ADD COLUMN featured;
